/***

  Oak Video Editor - Non-Linear Video Editor
  Copyright (C) 2026 Oak Team

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.

***/

#include "subtitleparams.h"

#include <cstdio>

namespace olive
{

std::string SubtitleParams::generate_ass_header()
{
	// NOTE: We'll probably implement more customization as we support ASS better. Right now, we only
	//       natively support SRT and only make this header because FFmpeg requires it.
	static const int k_ass_default_play_res_x = 384;
	static const int k_ass_default_play_res_y = 288;
	static const char *k_ass_default_font = "Arial";
	static const int k_ass_default_font_size = 16;
	static const int k_ass_default_primary_color = 0xFFFFFF; // White
	static const int k_ass_default_secondary_color = 0xFFFFFF; // White
	static const int k_ass_default_outline_color = 0x000000; // Black
	static const int k_ass_default_back_color = 0x000000; // Black
	static const int k_ass_bold = 0;
	static const int k_ass_italic = 0;
	static const int k_ass_underline = 0;
	static const int k_ass_strike = 0;
	static const int k_ass_border_style = 1;
	static const int k_ass_alignment = 2;

	std::string ass_code;
	char buf[256];

	// Header info
	// De-Qt note: the original used QCoreApplication::applicationName()/
	// applicationVersion(); oakcommon has no application object, so a fixed
	// generator name is emitted instead.
	ass_code.append("[Script Info]\r\n");
	ass_code.append("; Script generated by Oak\r\n");
	ass_code.append("ScriptType: v4.00+\r\n");
	std::snprintf(buf, sizeof(buf), "PlayResX: %d\r\n", k_ass_default_play_res_x);
	ass_code.append(buf);
	std::snprintf(buf, sizeof(buf), "PlayResY: %d\r\n", k_ass_default_play_res_y);
	ass_code.append(buf);
	ass_code.append("ScaledBorderAndShadow: yes\r\n");
	ass_code.append("\r\n");

	// ASSv4 header
	ass_code.append("[V4+ Styles]\r\n");
	ass_code.append("Format: Name, ");
	ass_code.append("Fontname, Fontsize, ");
	ass_code.append("PrimaryColour, SecondaryColour, OutlineColour, BackColour, ");
	ass_code.append("Bold, Italic, Underline, StrikeOut, ");
	ass_code.append("ScaleX, ScaleY, ");
	ass_code.append("Spacing, Angle, ");
	ass_code.append("BorderStyle, Outline, Shadow, ");
	ass_code.append("Alignment, MarginL, MarginR, MarginV, ");
	ass_code.append("Encoding\r\n");
	ass_code.append("Style: ");

	// Name
	ass_code.append("Default,");

	// Font{name,size}
	std::snprintf(buf, sizeof(buf), "%s,%d,", k_ass_default_font,
				  k_ass_default_font_size);
	ass_code.append(buf);

	// {Primary,Secondary,Outline,Back}Colour
	std::snprintf(buf, sizeof(buf), "&H%X,&H%X,&H%X,&H%X,",
				  k_ass_default_primary_color, k_ass_default_secondary_color,
				  k_ass_default_outline_color, k_ass_default_back_color);
	ass_code.append(buf);

	// Bold, Italic, Underline, StrikeOut
	std::snprintf(buf, sizeof(buf), "%d,%d,%d,%d,", k_ass_bold, k_ass_italic,
				  k_ass_underline, k_ass_strike);
	ass_code.append(buf);

	// Scale{X,Y}
	ass_code.append("100,100,");

	// Spacing, Angle
	ass_code.append("0,0,");

	// BorderStyle, Outline, Shadow
	std::snprintf(buf, sizeof(buf), "%d,1,0,", k_ass_border_style);
	ass_code.append(buf);

	// Alignment, Margin[LRV]
	std::snprintf(buf, sizeof(buf), "%d,10,10,10,", k_ass_alignment);
	ass_code.append(buf);

	// Encoding
	ass_code.append("0\r\n");
	ass_code.append("\r\n");
	ass_code.append("[Events]\r\n");
	ass_code.append(
		"Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\r\n");

	return ass_code;
}

void SubtitleParams::load(XmlStreamReader *reader)
{
	this->clear();

	while (xml_read_next_start_element(reader)) {
		const std::string &name = reader->name();
		if (name == "streamindex") {
			set_stream_index(std::stoi(reader->read_element_text()));
		} else if (name == "enabled") {
			set_enabled(std::stoi(reader->read_element_text()));
		} else if (name == "subtitles") {
			while (xml_read_next_start_element(reader)) {
				if (reader->name() == "subtitle") {
					Rational in, out;

					for (const XmlStreamAttribute &attr : reader->attributes()) {
						if (attr.name == "in") {
							in = Rational::from_string(attr.value);
						} else if (attr.name == "out") {
							out = Rational::from_string(attr.value);
						}
					}

					std::string text = reader->read_element_text();

					this->push_back(Subtitle(TimeRange(in, out), text));
				} else {
					reader->skip_current_element();
				}
			}
		} else {
			reader->skip_current_element();
		}
	}
}

void SubtitleParams::save(XmlStreamWriter *writer) const
{
	writer->write_text_element("streamindex", std::to_string(stream_index_));
	writer->write_text_element("enabled", std::to_string(enabled_));

	writer->write_start_element("subtitles");
	for (auto it = this->cbegin(); it != this->cend(); it++) {
		writer->write_start_element("subtitle");
		writer->write_attribute("in", it->time().in().to_string());
		writer->write_attribute("out", it->time().out().to_string());
		writer->write_characters(it->text());
		writer->write_end_element(); // subtitle
	}
	writer->write_end_element(); // subtitles
}

}
