/***

  Olive - Non-Linear Video Editor
  Copyright (C) 2022 Olive Team
  Modifications Copyright (C) 2025 mikesolar

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.

***/

#ifndef OAK_RENDERTICKET_H
#define OAK_RENDERTICKET_H

#include <condition_variable>
#include <functional>
#include <map>
#include <mutex>
#include <string>

#include "common/cancelableobject.h"
#include "variant.h"

namespace olive
{

class RenderTicket : public CancelableObject {
public:
	RenderTicket();

	virtual ~RenderTicket() override = default;

	/**
   * @brief Get the ticket's current state
   *
   * This function is thread safe, unless `lock` is set to false. Then the caller has responsibility
   * of locking the mutex before and unlocking after this function is called.
   */
	bool is_running(bool lock = true);

	/**
   * @brief Determine how many times ticket has been finished
   *
   * This function is thread safe, unless `lock` is set to false. Then the caller has responsibility
   * of locking the mutex before and unlocking after this function is called.
   */
	int get_finish_count(bool lock = true);

	/**
   * @brief Check if this ticket has a result
   *
   * If this ticket is running, this will always return false.
   */
	bool has_result();

	/**
   * @brief Get value, if any
   */
	Variant get();

	/**
   * @brief Wait for ticket to be finished
   *
   * If this ticket is not running, this function returns immediately.
   */
	void wait_for_finished();

	/**
   * @brief Access this ticket's mutex
   *
   * Use if you're doing several operations on a ticket and need to ensure thread safety while
   * doing so. Most of the time this isn't necessary since all functions are thread safe by default.
   */
	std::mutex *lock()
	{
		return &lock_;
	}

	/**
   * @brief Signal to the ticket that it is running
   *
   * If any value is set, it is cleared.
   */
	void start();

	/**
   * @brief Finish ticket with no value
   *
   * Sets ticket to no longer running and assume it has received no result.
   */
	void finish();

	/**
   * @brief Finish ticket with value
   *
   * Sets ticket to no longer running and provide a value generated by the operation requested.
   */
	void finish(Variant result);

	/**
   * @brief Set the callback invoked when finish has been called by any means
   *        (either cancelled or with a result)
   *
   * Replaces the former `finished` signal. The callback runs on the thread
   * that called finish(), after the ticket lock has been released.
   */
	void set_finished_callback(std::function<void()> cb)
	{
		std::lock_guard<std::mutex> locker(lock_);
		finished_callback_ = std::move(cb);
	}

	/**
   * @brief Dynamic property bag, replacing QObject::setProperty/property
   *
   * RenderManager packs render parameters onto the ticket and
   * RenderProcessor/RenderWorkerPool read them back. A missing name returns
   * a null Variant (QVariant-invalid semantics).
   */
	void set_property(const std::string &name, const Variant &value)
	{
		std::lock_guard<std::mutex> locker(lock_);
		properties_[name] = value;
	}

	Variant property(const std::string &name) const
	{
		std::lock_guard<std::mutex> locker(lock_);
		auto it = properties_.find(name);
		return it == properties_.end() ? Variant() : it->second;
	}

private:
	void finish_internal(bool has_result, Variant result);

	bool is_running_;

	Variant result_;

	bool has_result_;

	int finish_count_;

	// mutable: property() is const but still serializes against set_property()
	mutable std::mutex lock_;

	std::condition_variable wait_;

	std::function<void()> finished_callback_;

	std::map<std::string, Variant> properties_;
};

using RenderTicketPtr = std::shared_ptr<RenderTicket>;

class RenderTicketWatcher {
public:
	RenderTicketWatcher();

	RenderTicketPtr get_ticket() const
	{
		return ticket_;
	}

	void set_ticket(RenderTicketPtr ticket);

	bool is_running();

	void wait_for_finished();

	Variant get();

	bool has_result();

	void cancel();

	/**
   * @brief Set the callback replacing the former finished(watcher) signal
   */
	void set_finished_callback(std::function<void(RenderTicketWatcher *)> cb)
	{
		finished_callback_ = std::move(cb);
	}

	/**
   * @brief Dynamic property bag, replacing QObject::setProperty/property
   *
   * PreviewAutoCacher packs job/cache/time/node onto the watcher before the
   * ticket exists, so the bag lives on the watcher itself (as the QObject
   * original did). A missing name returns a null Variant.
   */
	void set_property(const std::string &name, const Variant &value)
	{
		std::lock_guard<std::mutex> locker(property_lock_);
		properties_[name] = value;
	}

	Variant property(const std::string &name) const
	{
		std::lock_guard<std::mutex> locker(property_lock_);
		auto it = properties_.find(name);
		return it == properties_.end() ? Variant() : it->second;
	}

private:
	RenderTicketPtr ticket_;

	std::function<void(RenderTicketWatcher *)> finished_callback_;

	mutable std::mutex property_lock_;
	std::map<std::string, Variant> properties_;

	void ticket_finished();
};

}

#endif // OAK_RENDERTICKET_H
