/*
 * Oak Video Editor - Non-Linear Video Editor
 * Copyright (C) 2026 Oak Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef OAK_PROXYMANAGER_H
#define OAK_PROXYMANAGER_H

#include <string>

namespace olive
{

/**
 * @brief Manages proxy (lower-res stand-in) generation
 *
 * Qt-free interim state: actual proxy transcodes are delegated to the
 * global task submit callback (include/codec/task.h). While no callback
 * is registered (pre-M8), get_or_start_proxy() reports the proxy as
 * missing instead of starting background work.
 *
 * Behavior changes vs. the Qt version:
 * - The `proxy_ready`/`proxy_finished` signals are gone; completion
 *   notification is the task system's / facade's business.
 * - Submission is synchronous: get_or_start_proxy() calls the submit
 *   callback inline and re-derives the state from the filesystem.
 * - proxy_params_from_config() returns compiled-in defaults until the
 *   config milestone wires a real store.
 */
class ProxyManager {
public:
	static void create_instance()
	{
		if (!instance_) {
			instance_ = new ProxyManager();
		}
	}

	static void destroy_instance()
	{
		delete instance_;
		instance_ = nullptr;
	}

	static ProxyManager *instance()
	{
		return instance_;
	}

	enum ProxyState {
		k_proxy_missing,
		k_proxy_generating,
		k_proxy_ready,
		k_proxy_failed
	};

	struct ProxyParams {
		int width = 1280;
		int height = 720;
		/**
		 * @brief Source resolution divider (1 = use absolute width/height,
		 * 2/4/8 = fraction of the source resolution)
		 */
		int divider = 1;
		int version = 1;
		std::string extension = "mp4";
		int crf = 23;
		std::string preset = "veryfast";
		bool include_audio = true;
	};

	struct Proxy {
		ProxyState state = k_proxy_missing;
		std::string filename;
	};

	static std::string get_proxy_directory(const std::string &cache_path);

	static std::string get_proxy_filename(const std::string &cache_path,
										  const std::string &source_filename,
										  int stream_index,
										  const ProxyParams &params);

	static std::string get_working_proxy_filename(const std::string &proxy_filename);

	static ProxyState get_proxy_state(const std::string &proxy_filename);

	static std::string proxy_state_to_string(ProxyState state);

	static ProxyState proxy_state_from_string(const std::string &state);

	/**
	 * @brief Returns true if a proxy filename generated by GetProxyFilename()
	 * indicates the proxy contains audio streams
	 */
	static bool proxy_filename_has_audio(const std::string &proxy_filename);

	/**
	 * @brief Builds proxy parameters from the global application config
	 *
	 * Interim state: returns the compiled-in defaults (1280x720, divider 1,
	 * mp4, crf 23, veryfast, audio included); the config milestone wires
	 * the real store.
	 */
	static ProxyParams proxy_params_from_config();

	/**
	 * @brief Locates an ffmpeg executable for proxy generation
	 *
	 * Resolution order: the explicitly configured path (if non-empty and an
	 * existing executable file), then the system PATH, then common
	 * platform-specific install locations. Returns an empty string if no
	 * executable could be found.
	 */
	static std::string find_f_fmpeg_executable(const std::string &configured_path);

	Proxy get_or_start_proxy(const std::string &cache_path,
							 const std::string &source_filename, int stream_index,
							 const ProxyParams &params);

private:
	ProxyManager() = default;

	static ProxyManager *instance_;
};

} // namespace olive

#endif // OAK_PROXYMANAGER_H
